hero_banner_img_1:
  default: 轮播图图片
  type: string

hero_banner_url_1:
  default: 轮播图链接地址
  type: string

hero_banner_img_2:
  default: 轮播图图片
  type: string

hero_banner_url_2:
  default: 轮播图链接地址
  type: string

hero_banner_img_3:
  default: 轮播图图片
  type: string

hero_banner_url_3:
  default: 轮播图链接地址
  type: string

top_banner_img_1:
  default: 推荐话题图片
  type: string

top_banner_title_1:
  default: 推荐话题标题
  type: string

top_banner_subtitle_1:
  default: 推荐话题子标题
  type: string

top_banner_url_1:
  default: 推荐话题子标题
  type: string

top_banner_img_2:
  default: 推荐话题图片
  type: string

top_banner_title_2:
  default: 推荐话题标题
  type: string

top_banner_subtitle_2:
  default: 推荐话题子标题
  type: string

top_banner_url_2:
  default: 推荐话题子标题
  type: string

top_banner_img_3:
  default: 推荐话题图片
  type: string

top_banner_title_3:
  default: 推荐话题标题
  type: string

top_banner_subtitle_3:
  default: 推荐话题子标题
  type: string

top_banner_url_3:
  default: 推荐话题子标题
  type: string
