hero_banner_1:
  img:
    default: https://bbs.ui.com.cm/
    type: string
    description: "轮播图图片"

  url:
    default: https://bbs.ui.com.cm/
    type: string
    description: "轮播图链接地址"

hero_banner_2:
  img:
    default: https://bbs.ui.com.cm/
    type: string
    description: "轮播图图片"

  url:
    default: https://bbs.ui.com.cm/
    type: string
    description: "轮播图链接地址"

hero_banner_3:
  img:
    default: https://bbs.ui.com.cm/
    type: string
    description: "轮播图图片"

  url:
    default: https://bbs.ui.com.cm/
    type: string
    description: "轮播图链接地址"

top_banner_1:
  img:
    default: https://bbs.ui.com.cm/
    type: string

  title:
    default: 标题
    type: string

  subtitle:
    default: 子标题
    type: string

  url:
    default: https://bbs.ui.com.cm/
    type: string
    description: "推荐话题链接地址"

top_banner_2:
  img:
    default: https://bbs.ui.com.cm/
    type: string

  title:
    default: 标题
    type: string

  subtitle:
    default: 子标题
    type: string

  url:
    default: https://bbs.ui.com.cm/
    type: string
    description: "推荐话题链接地址"

top_banner_3:
  img:
    default: https://bbs.ui.com.cm/
    type: string

  title:
    default: 标题
    type: string

  subtitle:
    default: 子标题
    type: string

  url:
    default: https://bbs.ui.com.cm/
    type: string
    description: "推荐话题链接地址"